---
language: ruby
bundler_args: --without system_tests
install: ["travis_retry ./.travis.sh"]
script: ["bundle exec rake validate", "bundle exec rake lint", "AUGEAS_LENS_LIB=files/lenses bundle exec rake spec SPEC_OPTS='--format documentation'", "bundle exec rake metadata"]
matrix:
  fast_finish: true
  include:
  - rvm: 1.8.7
    env: PUPPET_GEM_VERSION="~> 3.0" FACTER_GEM_VERSION="~> 1.7.0"
  - rvm: 1.9.3
    env: PUPPET_GEM_VERSION="~> 3.0"
  - rvm: 2.0.0
    env: PUPPET_GEM_VERSION="~> 3.0"
  - rvm: 2.0.0
    env: PUPPET_GEM_VERSION="~> 3.0" FUTURE_PARSER="yes"
  - rvm: 2.1.6
    env: PUPPET_GEM_VERSION="~> 4.0"
  - rvm: default
    sudo: required
    services: docker
    env: BEAKER_set="debian-7-x86_64-docker" PUPPET_AIO="yes"
    bundler_args: 
    script: bundle exec rspec spec/acceptance/*_spec.rb
  - rvm: default
    sudo: required
    services: docker
    env: BEAKER_set="debian-8-x86_64-docker" PUPPET_AIO="yes"
    bundler_args: 
    script: bundle exec rspec spec/acceptance/*_spec.rb
  - rvm: default
    sudo: required
    services: docker
    env: BEAKER_set="centos-6-x86_64-docker" PUPPET_AIO="yes"
    bundler_args: 
    script: bundle exec rspec spec/acceptance/*_spec.rb
  - rvm: default
    sudo: required
    services: docker
    env: BEAKER_set="centos-7-x86_64-docker" PUPPET_AIO="yes"
    bundler_args: 
    script: bundle exec rspec spec/acceptance/*_spec.rb
  - rvm: default
    sudo: required
    services: docker
    env: BEAKER_set="debian-7-x86_64-docker"
    bundler_args:
    script: sudo service docker restart ; sleep 10 && bundle exec rspec spec/acceptance/*_spec.rb
  - rvm: default
    sudo: required
    services: docker
    env: BEAKER_set="debian-8-x86_64-docker"
    bundler_args:
    script: bundle exec rspec spec/acceptance/*_spec.rb
  - rvm: default
    sudo: required
    services: docker
    env: BEAKER_set="centos-6-x86_64-docker"
    bundler_args:
    script: sudo service docker restart ; sleep 10 && bundle exec rspec spec/acceptance/*_spec.rb
  - rvm: default
    sudo: required
    services: docker
    env: BEAKER_set="centos-7-x86_64-docker"
    bundler_args:
    script: sudo service docker restart ; sleep 10 && bundle exec rspec spec/acceptance/*_spec.rb
notifications:
  email: false
deploy:
  provider: puppetforge
  user: camptocamp
  password:
    secure: "QcG6iRpDC8ojkaCsrO3HVyBCspKcc2lkxRlBLG5X61Gp8dytr36tzndldMsxGW4CgTnCWNuRlJhfKwvH8ObSR8hDZyQkNwzoOSRMIUM9SGvHKqCScSMW1gjdNvh/0oMt/WbZEcyN7/XIEmQqtMmXShBaQ0yWYdp3TvgfNSJ/NdM="
  on:
    tags: true
    # all_branches is required to use tags
    all_branches: true
    # Only publish if our main Ruby target builds
    rvm: 1.9.3
